web:
  image: deviavir/terraform-ci
  env_file:
    - secrets.env
  links:
    - rabbit
  ports:
    - 5000:5000
  command: "flask run --host=0.0.0.0"
worker:
  image: deviavir/terraform-ci
  env_file:
    - secrets.env
  environment:
    - C_FORCE_ROOT=true
  links:
    - rabbit
  volumes:
    - /your/terraform/directory:/terraform
  command: "celery --app=worker:app worker"

rabbit:
  image: rabbitmq:alpine
